services:
  usuarios-app:
    build: .
    container_name: usuarios-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge